
spring:
#  #  文件上传配置
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 100MB
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie
      username: root
      password: 1234
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
#      动态路径
reggie:
  path: C:\img\
#阿里云配置oss
aliyun:
  oss:
    endpoint:https: //oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tGne1B46E3doqCHreHU
    accessKeySecret : qGfqpaVbKLbz7PXGkcUUQTanu2VeHI
    bucketName : web-tlias-mybatis